export const productsByCategory = [
  {
    category: 'Tintas',
    items: [
      {
        id: '1e11d4f5-4f42-4d33-8c23-3345b5461a7a',
        title: 'Tinta Borracha Liquida Solução Total - Decor Color',
        price: 'R$ 699,22',
        description: 'ou até 12x de R$ 66,50',
        cardAppend: 'Compare entre 4 lojas',
        imageSrc: require('../../assets/products-images/tinta-borracha.png'),
        stores: [
          {
            name: 'Goiás Construções',
            price: 'R$ 699,22',
            location: 'Ver localização',
            isBestSeller: true,
          },
          {
            name: 'ConstruShop',
            price: 'R$ 719,90',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Casa & Construção',
            price: 'R$ 725,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'MegaTintas',
            price: 'R$ 730,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
        ],
      },
      {
        id: '2a23c5f6-7a66-4e78-b2f1-8832f4f3c9e9',
        title: 'Tinta Acrílica Fosca Premium - Coral',
        price: 'R$ 489,90',
        description: 'ou até 10x de R$ 49,90',
        cardAppend: 'Compare entre 3 lojas',
        imageSrc: require('../../assets/products-images/tinta-coral.png'),
        stores: [
          {
            name: 'Tintas ABC',
            price: 'R$ 480,00',
            location: 'Ver localização',
            isBestSeller: true,
          },
          {
            name: 'Goiás Construções',
            price: 'R$ 489,90',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Casa & Construção',
            price: 'R$ 499,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
        ],
      },
      {
        id: '3b37d7a8-8b99-4c67-a6f4-1125f7e2d6b3',
        title: 'Tinta Esmalte Sintético Brilhante - Suvinil',
        price: 'R$ 239,99',
        description: 'ou até 6x de R$ 40,00',
        cardAppend: 'Compare entre 5 lojas',
        imageSrc: require('../../assets/products-images/tinta-parede.png'),
        stores: [
          {
            name: 'Goiás Construções',
            price: 'R$ 239,99',
            location: 'Ver localização',
            isBestSeller: true,
          },
          {
            name: 'MegaTintas',
            price: 'R$ 249,99',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'ConstruShop',
            price: 'R$ 250,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Casa & Construção',
            price: 'R$ 255,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Tintas ABC',
            price: 'R$ 260,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
        ],
      },
    ],
  },
  {
    category: 'Pisos e Revestimentos',
    items: [
      {
        id: '4c46e9b9-5d88-4e47-b9d6-2235f9a1c2d4',
        title: 'Porcelanato Polido - 60x60cm - Portobello',
        price: 'R$ 1.299,90',
        description: 'ou até 12x de R$ 108,32',
        cardAppend: 'Compare entre 6 lojas',
        imageSrc: require('../../assets/products-images/porcelanato.png'),
        stores: [
          {
            name: 'RevestirBem',
            price: 'R$ 1.250,00',
            location: 'Ver localização',
            isBestSeller: true,
          },
          {
            name: 'ConstruShop',
            price: 'R$ 1.299,90',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Casa & Construção',
            price: 'R$ 1.320,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Goiás Construções',
            price: 'R$ 1.350,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'MegaTintas',
            price: 'R$ 1.360,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Tintas ABC',
            price: 'R$ 1.380,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
        ],
      },
      {
        id: '5d56f1c1-2a22-4f33-a1b7-3347e1f4d9e5',
        title: 'Piso Vinílico Eucafloor - 5mm - Eucatex',
        price: 'R$ 89,90',
        description: 'ou até 3x de R$ 29,97',
        cardAppend: 'Compare entre 2 lojas',
        imageSrc: require('../../assets/products-images/pisos-e-revestimentos.png'),
        stores: [
          {
            name: 'Casa & Construção',
            price: 'R$ 85,00',
            location: 'Ver localização',
            isBestSeller: true,
          },
          {
            name: 'Goiás Construções',
            price: 'R$ 89,90',
            location: 'Ver localização',
            isBestSeller: false,
          },
        ],
      },
      {
        id: '6e66f2d2-3b33-4f88-c2f8-4458f6f5e8f6',
        title: 'Revestimento Cerâmico 30x90cm - Ceusa',
        price: 'R$ 239,90',
        description: 'ou até 5x de R$ 47,98',
        cardAppend: 'Compare entre 4 lojas',
        imageSrc: require('../../assets/products-images/piso-madeira.png'),
        stores: [
          {
            name: 'ConstruShop',
            price: 'R$ 235,00',
            location: 'Ver localização',
            isBestSeller: true,
          },
          {
            name: 'RevestirBem',
            price: 'R$ 239,90',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Goiás Construções',
            price: 'R$ 245,00',
            location: 'Ver localização',
            isBestSeller: false,
          },
          {
            name: 'Casa & Construção',
            price: 'R$ 249,99',
            location: 'Ver localização',
            isBestSeller: false,
          },
        ],
      },
    ],
  },
]
