/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/api/auth/token/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Takes a set of user credentials and returns an access and refresh JSON web
     *     token pair to prove the authentication of those credentials.
     */
    post: operations['auth_token_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/token/refresh/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     *     token if the refresh token is valid.
     */
    post: operations['auth_token_refresh_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/categories/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['stores_categories_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/categories/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['stores_categories_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/products/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['stores_products_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/products/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['stores_products_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/products/{product_pk}/characteristics/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Endpoint que lida com as caraterísticas técnicas dos produtos */
    get: operations['stores_products_characteristics_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/products/{product_pk}/characteristics/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Endpoint que lida com as caraterísticas técnicas dos produtos */
    get: operations['stores_products_characteristics_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/products/{product_pk}/historic/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Endpoint que lida com os históricos de preços dos produtos */
    get: operations['stores_products_historic_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/products/{product_pk}/historic/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Endpoint que lida com os históricos de preços dos produtos */
    get: operations['stores_products_historic_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/products/{product_pk}/historic/last/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Retorna o preço atual do produto */
    get: operations['stores_products_historic_last_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stores/products/promotions/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['stores_products_promotions_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/users/me/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Obtem os dados do usuário logado */
    get: operations['users_me_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export type components = {
  schemas: {
    AuthTokenResponseSchema: {
      refresh: string
      access: string
      user: components['schemas']['User']
    } & {
      [key: string]: unknown
    }
    Category: {
      readonly id: number
      /** Nome */
      name: string
    } & {
      [key: string]: unknown
    }
    CategorySvg: {
      readonly id: number
      readonly svg: string
      /** Nome */
      name: string
    } & {
      [key: string]: unknown
    }
    Nested: {
      readonly id: number
      /** Nome */
      name: string
    } & {
      [key: string]: unknown
    }
    PaginatedPriceCharacteristicsList: {
      /** @example 123 */
      count?: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results?: components['schemas']['PriceCharacteristics'][]
    } & {
      [key: string]: unknown
    }
    PaginatedPriceHistoryList: {
      /** @example 123 */
      count?: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results?: components['schemas']['PriceHistory'][]
    } & {
      [key: string]: unknown
    }
    PaginatedProductList: {
      /** @example 123 */
      count?: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null
      results?: components['schemas']['Product'][]
    } & {
      [key: string]: unknown
    }
    PriceCharacteristics: {
      /** Nome da Característica */
      key: string
      /** Característica */
      value: string
    } & {
      [key: string]: unknown
    }
    PriceHistory: {
      /**
       * Preço
       * Format: decimal
       */
      price: string
      /** Format: date-time */
      readonly created_at: string
    } & {
      [key: string]: unknown
    }
    Product: {
      readonly id: number
      readonly category: components['schemas']['Category']
      /** Nome */
      name: string
      /**
       * Sobre
       * @description Sobre o produto
       */
      about: string
      /** Quantidade disponível */
      quantity: number
      /**
       * Preço
       * Format: decimal
       */
      price: string
      /**
       * Imagem
       * Format: uri
       */
      image?: string | null
      readonly store: components['schemas']['Nested']
    } & {
      [key: string]: unknown
    }
    TokenObtainPair: {
      email: string
      password: string
    } & {
      [key: string]: unknown
    }
    TokenRefresh: {
      readonly access: string
      refresh: string
    } & {
      [key: string]: unknown
    }
    User: {
      readonly id: number
      /**
       * Último login
       * Format: date-time
       */
      last_login?: string | null
      /**
       * E-mail
       * Format: email
       */
      email?: string
      /** Nome */
      name: string
      /**
       * Data de registro
       * Format: date-time
       */
      date_joined?: string
    } & {
      [key: string]: unknown
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = {
  auth_token_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenObtainPair']
        'application/x-www-form-urlencoded': components['schemas']['TokenObtainPair']
        'multipart/form-data': components['schemas']['TokenObtainPair']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthTokenResponseSchema']
        }
      }
    }
  }
  auth_token_refresh_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenRefresh']
        'application/x-www-form-urlencoded': components['schemas']['TokenRefresh']
        'multipart/form-data': components['schemas']['TokenRefresh']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenRefresh']
        }
      }
    }
  }
  stores_categories_list: {
    parameters: {
      query?: {
        /** @description Cor do path do SVG */
        fill_path?: string
        /** @description Cor do SVG */
        fill_svg?: string
        /** @description Altura do SVG */
        height?: string
        /** @description Largura do SVG */
        width?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategorySvg'][]
        }
      }
    }
  }
  stores_categories_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this Categoria. */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategorySvg']
        }
      }
    }
  }
  stores_products_list: {
    parameters: {
      query?: {
        /** @description Filtrar por Categoria */
        category?: string
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
        /** @description A search term. */
        search?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedProductList']
        }
      }
    }
  }
  stores_products_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this Produto. */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Product']
        }
      }
    }
  }
  stores_products_characteristics_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
      }
      header?: never
      path: {
        product_pk: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedPriceCharacteristicsList']
        }
      }
    }
  }
  stores_products_characteristics_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this Caracteristica Técnica do Produto. */
        id: number
        product_pk: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PriceCharacteristics']
        }
      }
    }
  }
  stores_products_historic_list: {
    parameters: {
      query?: {
        /** @description Filtrar por created at (com o lookup: lte) */
        end_at?: string
        /** @description Number of results to return per page. */
        limit?: number
        /** @description The initial index from which to return the results. */
        offset?: number
        /** @description Filtrar por created at (com o lookup: gte) */
        start_at?: string
      }
      header?: never
      path: {
        product_pk: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedPriceHistoryList']
        }
      }
    }
  }
  stores_products_historic_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this Histórico de preço de produto. */
        id: number
        product_pk: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PriceHistory']
        }
      }
    }
  }
  stores_products_historic_last_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        product_pk: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PriceHistory']
        }
      }
    }
  }
  stores_products_promotions_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Product']
        }
      }
    }
  }
  users_me_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
}
